---
- name: Verificando se o Maven já está instalado
  stat: 
    path: '{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}'
  register: maven_installed

- name: Downloading Maven
  get_url:
    url: '{{ maven_download_url }}'
    dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    url_username: '{{ maven_download_username }}'
    url_password: '{{ maven_download_password }}'
  when: not maven_installed.stat.exists
  become: yes

- name: Desempacotando Maven Binaries
  unarchive:
    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    copy: no
  when: not maven_installed.stat.exists
  become: yes

- name: Removendo configurações velhas
  file:
    path: /etc/profile.d/maven.sh
    state: absent
  become: yes

- name: Configurando Maven no PATH
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: '{{ item.line }}'
    create: yes
    state: present
  with_items:
    - { line: 'M2_HOME={{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}' }
    - { line: 'PATH=$PATH:$M2_HOME/bin' }
  become: yes

- name: Limpando lixo
  file:
    state: absent
    path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
  become: yes