  - 
    name: "Cria estrutura de diretório"
    command: "mkdir -p {{java_name}}"
    become: yes
  - 
    name: "Download Java"
    get_url: "url={{ jdk_tarball_url }}  dest={{ java_archive }} headers=\"Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'\" validate_certs=no owner=root group=root mode=744"
    become: yes
  - 
    name: "Desempacota arquivo"
    action: "shell tar -xzvf {{java_archive}} -C {{download_folder}}"
    become: yes
  - 
    name: "Define proprietário do diretório"
    file: "state=directory path={{java_name}} owner=root group=root recurse=yes"
    become: yes
  - 
    name: "Fazer Java disponível para o sistem pelo update-alternatives"
    command: "update-alternatives --install {{ java_name }} java {{ java_name }}/bin/java 0"
    become: yes
  - 
    name: "Define systemwide a variável de ambiente oracle.sh dentro do /etc/profile.d/"
    set_fact: "remote_file_path={{profile_path}}/oracle_jdk.sh"
    become: yes
  - 
    name: "Cria um novo arquivo {{profile_path}}/oracle_jdk.sh"
    file: "path={{remote_file_path}} state=touch"
    become: yes
  - 
    register: file_path
    stat: "path={{remote_file_path}}"
    become: yes
  - 
    name: "Set executable perission"
    copy: 
      content: |
          #!/bin/bash
          export JDK_HOME={{ java_name }}
          export JAVA_HOME={{ java_name }}
          export JRE_HOME={{ java_name }}/jre
          export PATH=$PATH:{{ java_name }}/bin:{{ java_name }}/jre/bin
      dest: /etc/profile.d/oracle_jdk.sh
    become: yes
  - 
    name: "Set executable perission"
    file: "path={{profile_path}}/oracle_jdk.sh owner=root group=root mode=0555 state=file recurse=no"
    become: yes
  - 
    name: "Source the file {{profile_path}}/oracle_jdk.sh"
    shell:  "source /etc/profile" 
    args: 
      executable: "/bin/bash"